version: "2.2"

# Node 1: 10.123.252.230
# Node 2: 10.123.252.197
# Node 3: 10.123.252.206

volumes:
  hadoop_namenode:
  hadoop_datanode:
  kafka:

networks:
  default:
    name: big-data-network
  namenode-private:

services:

  commits-connector:
    image: commits-connector
    container_name: commits-connector
    build: 
      context: ./Connectors/CommitConnector
    restart: on-failure
    volumes:
      - ./hadoop_spark_kafka/etc/hosts:/etc/hosts
    environment:
      - DAAB_SPARK_URL=spark-master:7077
      - DAAB_NAMENODE_URL=namenode:9000
      - DAAB_KAFKA_URL=kafka-1:9092,kafka-2:9092,kafka-3:9092

  content-connector:
    image: content-connector
    container_name: content-connector
    build: 
      context: ./Connectors/ContentConnector
    restart: on-failure
    volumes:
      - ./hadoop_spark_kafka/etc/hosts:/etc/hosts
    environment:
      - DAAB_SPARK_URL=spark-master:7077
      - DAAB_NAMENODE_URL=namenode:9000
      - DAAB_KAFKA_URL=kafka-1:9092,kafka-2:9092,kafka-3:9092

  language-connector:
    image: language-connector
    container_name: language-connector
    build: 
      context: ./Connectors/LanguageConnector
    restart: on-failure
    volumes:
      - ./hadoop_spark_kafka/etc/hosts:/etc/hosts
    environment:
      - DAAB_SPARK_URL=spark-master:7077
      - DAAB_NAMENODE_URL=namenode:9000
      - DAAB_KAFKA_URL=kafka-1:9092,kafka-2:9092,kafka-3:9092